

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BichoFelizMVC
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class BichoFelizMVCEntities : DbContext
{
    public BichoFelizMVCEntities()
        : base("name=BichoFelizMVCEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<CONTATO> CONTATO { get; set; }

    public DbSet<EMPRESA> EMPRESA { get; set; }

    public DbSet<LOGACESSO> LOGACESSO { get; set; }

    public DbSet<RACA> RACA { get; set; }

    public DbSet<TIPO> TIPO { get; set; }

    public DbSet<TIPOSERVICO> TIPOSERVICO { get; set; }

    public DbSet<USUARIO> USUARIO { get; set; }

    public DbSet<ANIMAL> ANIMAL { get; set; }

    public DbSet<SERVICO> SERVICO { get; set; }

}

}

