//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BichoFelizMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BichoFelizDBEntities : DbContext
    {
        public BichoFelizDBEntities()
            : base("name=BichoFelizDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ANIMAL> ANIMALs { get; set; }
        public DbSet<CONTATO> CONTATOes { get; set; }
        public DbSet<LOGACESSO> LOGACESSOes { get; set; }
        public DbSet<RACA> RACAs { get; set; }
        public DbSet<TIPO> TIPOes { get; set; }
        public DbSet<TIPOSERVICO> TIPOSERVICOes { get; set; }
        public DbSet<USUARIO> USUARIOs { get; set; }
        public DbSet<SERVICO> SERVICOes { get; set; }
    }
}
