
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BichoFelizMVC
{

using System;
    using System.Collections.Generic;
    
public partial class LOGACESSO
{

    public int IDTOKEN { get; set; }

    public Nullable<int> IDUSUARIO { get; set; }

    public string EMAIL { get; set; }

    public string TOKEN { get; set; }

    public Nullable<System.DateTime> DATAHORA { get; set; }



    public virtual USUARIO USUARIO { get; set; }

}

}
