
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BichoFelizMVC
{

using System;
    using System.Collections.Generic;
    
public partial class TIPOSERVICO
{

    public TIPOSERVICO()
    {

        this.SERVICO = new HashSet<SERVICO>();

    }


    public int IDTIPOSERVICO { get; set; }

    public string NOME { get; set; }



    public virtual ICollection<SERVICO> SERVICO { get; set; }

}

}
